### PR TITLE
Laravel messenger

### PR DESCRIPTION
**Pull request by rygos**
To integrate this into existing installations you have to do the following:
- composer update
- php artisan migrate
- add new setting: "module_active_pms" with value 1

Thats it. Please test this stuff =)

Todo: Add Breadcrumb Navigation on Top, unreaded Messages for Homepage Widget and (Maybe a task for you) integrate this into notification system =)

### CODE REVIEW

**Comment by lianguan** [comment]
Both of styleci and traivis-ci checks have failed.

**Comment by rygos** [comment]
Yes. Style Check is irrelevant. StyleCI is solve the problem itself.
travis-ci tells me, that the build does not work because of Duplicate Class name in Migration. I have solve this in the newest Commit.

Additional i have done the following Changes:
- add missing </ul> in create_edit.blade.php for Thread View and PMS
- fix some translation related stuff
- fix a route to Userprofile
- fix some triple {{{ }}} for Blade Variables
- add a button for Home-Widget to go to Inbox or Create Message

**Comment by rygos** [comment]
Now travis fails because of the ALTER TABLE Thing in add_nullable_to_last_read_in_participants_table. You have configured phpunit to use a sqlite database wich cannot alter tables... i check and send a fix commit.

**Comment by rygos** [comment]
Now it works for PHP, LLVM has some exceptions.

Any Suggestions?

**Pull request merged**
